# Generated by Django 5.2.6 on 2025-09-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_user_product_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
    ]
